export const color = {
  bg: {
    'overlay-dim': 'rgba(0, 0, 0, 0.6)',
    'layer-default': 'var(--color-cream-50)',
    'layer-deep': 'var(--color-cream-100)',
    'layer-elevated': 'var(--color-gray-0)',
    'brand-solid': 'var(--color-vermilion-500)',
    'brand-solid-pressed': 'var(--color-vermilion-600)',
    'brand-weak': 'var(--color-vermilion-50)',
    'brand-weak-pressed': 'var(--color-vermilion-100)',
    'interactive-solid': 'var(--color-blue-500)',
    'interactive-solid-pressed': 'var(--color-blue-600)',
    'interactive-weak': 'var(--color-blue-50)',
    'interactive-weak-pressed': 'var(--color-blue-100)',
    'informative-solid': 'var(--color-blue-500)',
    'informative-weak': 'var(--color-blue-50)',
    'negative-solid': 'var(--color-pink-500)',
    'negative-solid-pressed': 'var(--color-pink-600)',
    'negative-weak': 'var(--color-pink-50)',
    'negative-weak-pressed': 'var(--color-pink-100)',
    'highlight-weak': 'var(--color-yellow-50)',
    'highlight-solid': 'var(--color-yellow-500)',
    'neutral-weak': 'var(--color-gray-100)',
    'neutral-weak-pressed': 'var(--color-gray-200)',
    disabled: 'var(--color-gray-50)',
    'neutral-solid': 'var(--color-gray-700)',
    'neutral-solid-pressed': 'var(--color-gray-900)',
    'highlight-muted': 'var(--color-yellow-100)',
  },
  fg: {
    brand: 'var(--color-vermilion-600)',
    'brand-contrast': 'var(--color-vermilion-700)',
    interactive: 'var(--color-blue-600)',
    'interactive-contrast': 'var(--color-blue-700)',
    informative: 'var(--color-blue-600)',
    'informative-subtle': 'var(--color-gray-300)',
    'informative-contrast': 'var(--color-blue-700)',
    negative: 'var(--color-pink-700)',
    highlight: 'var(--color-yellow-700)',
    neutral: 'var(--color-gray-900)',
    'neutral-muted': 'var(--color-gray-700)',
    'neutral-subtle': 'var(--color-gray-500)',
    'neutral-faint': 'var(--color-gray-300)',
    placeholder: 'var(--color-gray-300)',
    disabled: 'var(--color-gray-300)',
    'on-solid': 'var(--color-static-white)',
  },
  stroke: {
    'neutral-weak': 'var(--color-gray-200)',
    'neutral-solid': 'var(--color-gray-600)',
    'neutral-subtle': 'var(--color-gray-100)',
    'brand-solid': 'var(--color-vermilion-500)',
    'brand-weak': 'var(--color-vermilion-200)',
    'interactive-solid': 'var(--color-blue-500)',
    'negative-solid': 'var(--color-pink-500)',
    'interactive-weak': 'var(--color-blue-200)',
    'negative-weak': 'var(--color-pink-200)',
  },
} as const;
